"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

def PentagonGen(n):
    l = []
    for i in range(1, n+1):
        l.append(i * ( 3 * i - 1 ) /2)
    return l

def TriangleGen(n):
    l = []
    for i in range(1, n+1):
        l.append((i * ( i + 1 )) /2)
    return l

def HexagonalGen(n):
    l = []
    for i in range(1, n+1):
        l.append(i * ( 2 * i - 1 ))
    return l

pen = PentagonGen(150000)
tri = TriangleGen(300000)
hex = HexagonalGen(150000)

def binarySearch(list, target):
    cursor = len(list)/2
    if list[cursor] == target:
        return True
    elif len(list) == 1:
        return False
    elif list[cursor] > target:
        return binarySearch(list[:cursor], target)
    else:
        return binarySearch(list[cursor/2 + 1:], target)

i = 0
for val in pen:
    if binarySearch(tri, val) and binarySearch(hex, val):
        print val
    if i % 10000 == 0:
        print i
    i+=1
